/// Flutter icons LineAwesome
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LineAwesome
///      fonts:
///       - asset: fonts/LineAwesome.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LineAwesome {
  LineAwesome._();

  static const _kFontFam = 'LineAwesome';

  static const IconData angle_left_1 = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData bar_chart_1 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData pencil_1 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData heart_1 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData angle_up_1 = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData adjust = const IconData(0xf101, fontFamily: _kFontFam);
  static const IconData angle_down = const IconData(0xf110, fontFamily: _kFontFam);
  static const IconData angle_left = const IconData(0xf111, fontFamily: _kFontFam);
  static const IconData angle_up = const IconData(0xf113, fontFamily: _kFontFam);
  static const IconData arrow_circle_down = const IconData(0xf117, fontFamily: _kFontFam);
  static const IconData arrows_alt = const IconData(0xf124, fontFamily: _kFontFam);
  static const IconData bar_chart = const IconData(0xf12e, fontFamily: _kFontFam);
  static const IconData bar_chart_o = const IconData(0xf12f, fontFamily: _kFontFam);
  static const IconData bell = const IconData(0xf140, fontFamily: _kFontFam);
  static const IconData birthday_cake = const IconData(0xf146, fontFamily: _kFontFam);
  static const IconData building = const IconData(0xf154, fontFamily: _kFontFam);
  static const IconData calendar_1 = const IconData(0xf15c, fontFamily: _kFontFam);
  static const IconData calendar_check_o = const IconData(0xf15d, fontFamily: _kFontFam);
  static const IconData calendar_times_o = const IconData(0xf161, fontFamily: _kFontFam);
  static const IconData camera_retro = const IconData(0xf163, fontFamily: _kFontFam);
  static const IconData check = const IconData(0xf17b, fontFamily: _kFontFam);
  static const IconData check_circle = const IconData(0xf17c, fontFamily: _kFontFam);
  static const IconData check_circle_o = const IconData(0xf17d, fontFamily: _kFontFam);
  static const IconData check_square = const IconData(0xf17e, fontFamily: _kFontFam);
  static const IconData check_square_o = const IconData(0xf17f, fontFamily: _kFontFam);
  static const IconData chevron_circle_down = const IconData(0xf180, fontFamily: _kFontFam);
  static const IconData clock_o = const IconData(0xf18f, fontFamily: _kFontFam);
  static const IconData clone = const IconData(0xf190, fontFamily: _kFontFam);
  static const IconData close = const IconData(0xf191, fontFamily: _kFontFam);
  static const IconData code = const IconData(0xf196, fontFamily: _kFontFam);
  static const IconData coffee = const IconData(0xf199, fontFamily: _kFontFam);
  static const IconData cog = const IconData(0xf19a, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xf19d, fontFamily: _kFontFam);
  static const IconData cube = const IconData(0xf1ae, fontFamily: _kFontFam);
  static const IconData dashboard = const IconData(0xf1b2, fontFamily: _kFontFam);
  static const IconData download = const IconData(0xf1bd, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xf1c1, fontFamily: _kFontFam);
  static const IconData envelope = const IconData(0xf1c6, fontFamily: _kFontFam);
  static const IconData expand = const IconData(0xf1d0, fontFamily: _kFontFam);
  static const IconData external_link = const IconData(0xf1d2, fontFamily: _kFontFam);
  static const IconData file_text = const IconData(0xf1ec, fontFamily: _kFontFam);
  static const IconData filter = const IconData(0xf1f3, fontFamily: _kFontFam);
  static const IconData flag = const IconData(0xf1f7, fontFamily: _kFontFam);
  static const IconData frown_o = const IconData(0xf207, fontFamily: _kFontFam);
  static const IconData gear = const IconData(0xf20c, fontFamily: _kFontFam);
  static const IconData github_square = const IconData(0xf217, fontFamily: _kFontFam);
  static const IconData group = const IconData(0xf220, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xf233, fontFamily: _kFontFam);
  static const IconData history = const IconData(0xf236, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xf237, fontFamily: _kFontFam);
  static const IconData keyboard_o = const IconData(0xf256, fontFamily: _kFontFam);
  static const IconData level_up = const IconData(0xf261, fontFamily: _kFontFam);
  static const IconData link = const IconData(0xf268, fontFamily: _kFontFam);
  static const IconData location_arrow = const IconData(0xf270, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xf271, fontFamily: _kFontFam);
  static const IconData long_arrow_down = const IconData(0xf272, fontFamily: _kFontFam);
  static const IconData long_arrow_left = const IconData(0xf273, fontFamily: _kFontFam);
  static const IconData mail_forward = const IconData(0xf278, fontFamily: _kFontFam);
  static const IconData map_marker = const IconData(0xf27d, fontFamily: _kFontFam);
  static const IconData meh_o = const IconData(0xf28a, fontFamily: _kFontFam);
  static const IconData money = const IconData(0xf294, fontFamily: _kFontFam);
  static const IconData pencil = const IconData(0xf2b0, fontFamily: _kFontFam);
  static const IconData pencil_square_o = const IconData(0xf2b2, fontFamily: _kFontFam);
  static const IconData photo = const IconData(0xf2b5, fontFamily: _kFontFam);
  static const IconData plus = const IconData(0xf2c2, fontFamily: _kFontFam);
  static const IconData refresh = const IconData(0xf2d5, fontFamily: _kFontFam);
  static const IconData save = const IconData(0xf2e9, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xf2eb, fontFamily: _kFontFam);
  static const IconData sign_in = const IconData(0xf2fb, fontFamily: _kFontFam);
  static const IconData sign_out = const IconData(0xf2fc, fontFamily: _kFontFam);
  static const IconData smile_o = const IconData(0xf305, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xf318, fontFamily: _kFontFam);
  static const IconData star_o = const IconData(0xf31b, fontFamily: _kFontFam);
  static const IconData sticky_note_o = const IconData(0xf322, fontFamily: _kFontFam);
  static const IconData terminal = const IconData(0xf336, fontFamily: _kFontFam);
  static const IconData thumbs_o_up = const IconData(0xf33f, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xf34c, fontFamily: _kFontFam);
  static const IconData trash_o = const IconData(0xf34d, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xf364, fontFamily: _kFontFam);
  static const IconData user_plus = const IconData(0xf366, fontFamily: _kFontFam);
}
